# ---- Database Secret ----
apiVersion: v1
kind: Secret
metadata:
  name: blooger-db-secret
  namespace: blooger
  labels:
    app.kubernetes.io/part-of: blooger
type: Opaque
stringData:
  POSTGRES_USER: jerney_user
  POSTGRES_PASSWORD: jerney_pass_2026 
  POSTGRES_DB: jerney_db
  # POSTGRES_DB: amVybmV5X2Ri |  base64 → echo -n "jerney_db" 
  # POSTGRES_USER: amVybmV5X3VzZXI= | base64 → echo -n "jerney_user" 
  # POSTGRES_PASSWORD: amVybmV5X3Bhc3NfMjAyNg== | base64 → echo -n "jerney_pass_2026" 