name: GitOps Pull Request

on:
  workflow_run:
    workflows:
      - "Blooger DevSecOps Pipeline"
    types:
      - completed

permissions:
  contents: read

jobs:
  update-gitops:

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    steps:

      ############################################################
      # Clone GitOps Repository
      ############################################################

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ak-devops-anurag-org/blooger-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      ############################################################
      # Install yq
      ############################################################

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
          https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

          sudo chmod +x /usr/local/bin/yq

      ############################################################
      # Update Helm Values
      ############################################################

      - name: Update Image Tags
        run: |

          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
          IMAGE_TAG=${IMAGE_TAG::7}

          cd gitops

          yq -i '.backend.image.tag = strenv(IMAGE_TAG)' charts/blooger/values.yaml

          yq -i '.frontend.image.tag = strenv(IMAGE_TAG)' charts/blooger/values.yaml

      ############################################################
      # Create Pull Request
      ############################################################

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITOPS_PAT }}

          path: gitops

          commit-message: |
            ci: update Blooger images to ${{ github.event.workflow_run.head_sha }}

          title: |
            Update Blooger Images

          body: |
            ## Automated Image Update

            This PR was created automatically by GitHub Actions.

            **Image Tag**

            `${{ github.event.workflow_run.head_sha }}`

          branch: |
            ci/update-images

          delete-branch: true

          base: main